version: '3'

services:

    ##### POSTGRES #####
    db:
        restart: always
        build: ./db
        volumes:
            - ./data/pgdb:/var/lib/postgresql/data:rw
        ports:
            - 5432:5432

    ##### APP #####
    app:
        restart: always
        user: "${uid}:${gid}"
        build: ./app
        tty: true
        volumes:
          - ./app:/usr/src/app:rw
        ports:
          - 8000:8000
        command: "python concierge/manage.py runserver 0.0.0.0:8000"
        depends_on:
          - db
