# Generated by Django 3.0.1 on 2020-01-04 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('max_guests', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='concierge.Apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=144)),
            ],
        ),
        migrations.CreateModel(
            name='KeyStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_on_hands', models.DateTimeField()),
                ('key_out_hands', models.DateTimeField()),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concierge.Key')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concierge.Person')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='tenant',
            field=models.OneToOneField(on_delete=models.SET('free'), to='concierge.Person'),
        ),
    ]
