# Generated by Django 3.0.1 on 2020-01-05 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Tenant',
        ),
    ]
