# Generated by Django 3.0.2 on 2020-01-09 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0003_auto_20200105_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_on_hands', models.DateTimeField(null=True)),
                ('key_is_back', models.DateTimeField(null=True)),
                ('comments', models.CharField(max_length=255, null=True)),
                ('guests', models.IntegerField(default=0)),
                ('key_is_kept', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='keystatus',
            name='key',
        ),
        migrations.RemoveField(
            model_name='keystatus',
            name='person_id',
        ),
        migrations.AddField(
            model_name='apartment',
            name='status',
            field=models.CharField(default='free', max_length=10),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='concierge.Tenant'),
        ),
        migrations.DeleteModel(
            name='Key',
        ),
        migrations.DeleteModel(
            name='KeyStatus',
        ),
        migrations.AddField(
            model_name='journal',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='concierge.Apartment'),
        ),
        migrations.AddField(
            model_name='journal',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concierge.Tenant'),
        ),
    ]
