# Generated by Django 3.0.2 on 2020-01-09 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0004_auto_20200109_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='concierge.Tenant'),
        ),
    ]
