# Generated by Django 3.0.2 on 2020-01-09 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('max_guests', models.IntegerField(null=True)),
                ('status', models.CharField(default='free', max_length=10)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mycore.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_on_hands', models.DateTimeField(null=True)),
                ('key_is_back', models.DateTimeField(null=True)),
                ('comments', models.CharField(max_length=255, null=True)),
                ('guests', models.IntegerField(default=0)),
                ('key_is_kept', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mycore.Room')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mycore.Tenant')),
            ],
        ),
    ]
