# Generated by Django 3.0.2 on 2020-01-26 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycore', '0003_auto_20200120_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'permissions': [('update_journal', 'Allows to update information in the DB')]},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'permissions': [('create_new_room', 'Allows to add new room to the DB')]},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['first_name', 'last_name'], 'permissions': [('create_new_tenant', 'Allows to add new tenant to the DB')]},
        ),
    ]
